"""add embedding and last_used to Interest

Revision ID: 49f70e4fcdbb
Revises: c43b814f5b12
Create Date: 2025-07-18 10:00:15.636169

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "49f70e4fcdbb"
down_revision: Union[str, Sequence[str], None] = "c43b814f5b12"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("interest", sa.Column("weight", sa.Float(), nullable=True))
    op.add_column("interest", sa.Column("last_used", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("interest", "embedding", existing_type=sa.BLOB(), nullable=True)
    op.drop_column("interest", "last_used")
    op.drop_column("interest", "weight")
    # ### end Alembic commands ###
