"""initial schema

Revision ID: c43b814f5b12
Revises: 
Create Date: 2025-07-17 23:35:42.548210

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c43b814f5b12"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "allowed_media",
        sa.Column("uri", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("uri"),
    )
    op.create_table(
        "bio_fact",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "care_plan",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trigger", sa.String(), nullable=True),
        sa.Column("intervention_uri", sa.String(), nullable=True),
        sa.Column("kind", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "interaction",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("user_input", sa.String(), nullable=False),
        sa.Column("llm_response", sa.String(), nullable=False),
        sa.Column("emotion_scores", sa.JSON(), nullable=False),
        sa.Column("safety_flag", sa.Boolean(), nullable=True),
        sa.Column("cognitive_score", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_interaction_timestamp"), "interaction", ["timestamp"], unique=False
    )
    op.create_table(
        "interest",
        sa.Column("tag", sa.String(), nullable=False),
        sa.Column("embedding", sa.LargeBinary(), nullable=True),
        sa.PrimaryKeyConstraint("tag"),
    )
    op.create_table(
        "lifeline_event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_lifeline_event_date"), "lifeline_event", ["date"], unique=False
    )
    op.create_table(
        "rate_limit_window",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("request_cnt", sa.Integer(), nullable=True),
        sa.Column("window_end", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rate_limit_window")
    op.drop_index(op.f("ix_lifeline_event_date"), table_name="lifeline_event")
    op.drop_table("lifeline_event")
    op.drop_table("interest")
    op.drop_index(op.f("ix_interaction_timestamp"), table_name="interaction")
    op.drop_table("interaction")
    op.drop_table("care_plan")
    op.drop_table("bio_fact")
    op.drop_table("allowed_media")
    # ### end Alembic commands ###
