name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.11'}

      - run: pip install -r requirements.txt
      - run: pip install -r requirements-dev.txt
      
      - name: Install runtime deps
        run: pip install -r requirements.lock
      - name: Set dummy secrets for tests
        run: |
          echo "OPENAI_API_KEY=dummy-ci-key" >> "$GITHUB_ENV"
          echo "TOKENIZERS_PARALLELISM=false" >> "$GITHUB_ENV"
          python - <<'PY'
          from cryptography.fernet import Fernet, os
          with open(os.environ["GITHUB_ENV"], "a") as fh:
              fh.write(f"LUCY_ENCRYPTION_KEY={Fernet.generate_key().decode()}\n")
          PY

      # 🧠 spaCy model
      - name: Download small spaCy model
        run: python -m spacy download en_core_web_sm

      - name: Run pre-commit (Black + Ruff)
        uses: pre-commit/action@v3.0.1

      - name: Run migrations
        run: alembic upgrade head

      - name: Run tests
        run: pytest -q

      - name: Run analysis plot tests
        run: pytest tests/test_analysis.py -q

      - name: Build Docker image
        run: docker build -t lucy:ci .